# Generated by Django 2.0.1 on 2018-01-27 10:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180127_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 27, 10, 50, 51, 726629, tzinfo=utc)),
        ),
    ]
