# Generated by Django 2.0.1 on 2018-01-27 10:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20180127_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
