# Generated by Django 2.0.1 on 2018-02-07 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_news_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date_created', '-date_updated'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
