# Generated by Django 2.0.1 on 2018-02-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20180207_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(db_index=True, default='Title', max_length=100, unique=True),
        ),
    ]
