# Generated by Django 2.0.1 on 2018-02-19 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20180212_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date_created', '-date_updated'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
