# Generated by Django 2.0.1 on 2018-02-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20180219_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(default='Title', max_length=100, verbose_name='Название'),
        ),
    ]
