# Generated by Django 2.0.1 on 2018-02-07 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile2',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile2',
        ),
    ]
