# Generated by Django 2.0.1 on 2018-02-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180210_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_url_period', models.SmallIntegerField(default=100, verbose_name='Срок действия ссылки на активацию, ч.')),
                ('default_user_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Аватар пользователя по умолчанию')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
