# Generated by Django 2.0.1 on 2018-02-10 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180210_1455'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteSettings',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='activation',
        ),
        migrations.DeleteModel(
            name='Activation',
        ),
    ]
