# Generated by Django 2.0.1 on 2018-02-10 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180210_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_until', models.DateTimeField(verbose_name='Дата окончания действия ссылки активации')),
                ('url', models.URLField(verbose_name='Ссылка')),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_url_period', models.SmallIntegerField(default=100, verbose_name='Срок действия ссылки на активацию, ч.')),
                ('default_user_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Аватар пользователя по умолчанию')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='activation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Activation', verbose_name='Активация'),
        ),
    ]
