# Generated by Django 2.0.1 on 2018-02-19 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Настройки'},
        ),
    ]
