# Generated by Django 2.0.1 on 2018-02-19 17:24

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180219_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='author',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='author',
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Site settings'},
        ),
        migrations.AlterField(
            model_name='activation',
            name='url',
            field=models.URLField(verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='activation',
            name='valid_until',
            field=models.DateTimeField(verbose_name='Activation URL valid until'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='activation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Activation', verbose_name='Activation'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.get_profile_image_path, verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='activation_url_preiod',
            field=models.SmallIntegerField(default=100, verbose_name='URL activity period, h.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='default_user_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Default user avatar'),
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
        migrations.DeleteModel(
            name='Homepage',
        ),
    ]
