# Generated by Django 2.0.1 on 2018-02-22 08:46

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180219_2024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Настройки сайта'},
        ),
        migrations.AlterField(
            model_name='activation',
            name='url',
            field=models.URLField(verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='activation',
            name='valid_until',
            field=models.DateTimeField(verbose_name='Ссылка активна до'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='activation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Activation', verbose_name='Активация'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.get_profile_image_path, verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='activation_url_preiod',
            field=models.SmallIntegerField(default=100, verbose_name='Время действия ссылки, ч'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='default_user_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Аватар по-умолчанию'),
        ),
    ]
