# Generated by Django 2.0.2 on 2018-02-24 16:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20180223_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_text',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_pic',
            field=models.ImageField(blank=True, null=True, upload_to='.', verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
