# Generated by Django 2.0.2 on 2018-02-24 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20180224_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_pic',
            new_name='pic',
        ),
    ]
