# Generated by Django 2.0.2 on 2018-02-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20180224_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='D:\\projects\\Kirill\\media', verbose_name='Картинка'),
        ),
    ]
