# Generated by Django 2.0.1 on 2018-02-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20180224_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(blank=True, null=True, verbose_name='Ингридиенты'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to='.', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Инструкция'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(default='Title', max_length=100, verbose_name='Название рецепта'),
        ),
    ]
